destination:
    owner: gardener-community
    repo: gardener-charts
sources:
    - name: garden-kube-apiserver
      version: v1.0.0
      repo: gardener-community/garden-kube-apiserver
      charts:
        - charts/garden-kube-apiserver
    - name: gardener-controlplane
      version: v1.53.0
      repo: gardener/gardener
      charts:
        - charts/gardener/controlplane
    - name: gardenlet
      version: v1.53.0
      repo: gardener/gardener
      charts:
        - charts/gardener/gardenlet
    - name: dashboard
      version: 1.60.0
      repo: gardener/dashboard
      charts:
        - charts/gardener-dashboard
    - name: identity
      version: 1.60.0
      repo: gardener/dashboard
      charts:
        - charts/identity
    - name: runtime-gvisor
      version: v0.5.1
      repo: gardener/gardener-extension-runtime-gvisor
      charts:
        - controller-registration
    - name: external-dns-management
      version: v0.13.0
      repo: gardener/external-dns-management
      charts:
        - controller-registration
    - name: networking-calico
      version: v1.25.0
      repo: gardener/gardener-extension-networking-calico
      charts:
        - controller-registration
    - name: networking-cilium
      version: v1.16.2
      repo: gardener/gardener-extension-networking-cilium
      charts:
        - controller-registration
    - name: os-gardenlinux
      version: v0.14.0
      repo: gardener/gardener-extension-os-gardenlinux
      charts:
        - controller-registration
    - name: os-ubuntu
      version: v1.18.0
      repo: gardener/gardener-extension-os-ubuntu
      charts:
        - controller-registration
    - name: provider-alicloud
      version: v1.39.0
      repo: gardener/gardener-extension-provider-alicloud
      charts:
        - controller-registration
    - name: provider-aws
      version: v1.37.0
      repo: gardener/gardener-extension-provider-aws
      charts:
        - controller-registration
    - name: provider-gcp
      version: v1.24.0
      repo: gardener/gardener-extension-provider-gcp
      charts:
        - controller-registration
    - name: provider-azure
      version: v1.29.0
      repo: gardener/gardener-extension-provider-azure
      charts:
        - controller-registration
        - charts/gardener-extension-admission-azure
    - name: provider-hcloud
      version: v0.5.6
      repo: 23technologies/gardener-extension-provider-hcloud
      charts:
        - controller-registration
    - name: provider-openstack
      version: v1.28.0
      repo: gardener/gardener-extension-provider-openstack
      charts:
        - controller-registration
    - name: shoot-cert-service
      version: v1.23.0
      repo: gardener/gardener-extension-shoot-cert-service
      charts:
        - controller-registration
    - name: shoot-dns-service
      version: v1.22.0
      repo: gardener/gardener-extension-shoot-dns-service
      charts:
        - controller-registration
targetdir: charts
