destination:
    owner: j2l4e
    repo: testtest
sources:
    - name: dashboard
      version: 1.68.0
      repo: gardener/dashboard
      charts:
        - charts/gardener-dashboard
targetdir: charts
